FROM nginx:1.25.5
LABEL maintainer"umeshpolavarapu71@gmail.com"LABEL version="1.25.5"
RUN apt-get update && apt-get install -y nginx
WORKDIR /home/umesh/Desktop
CMD ["sleep","1000"]
VOLUME /var/lib
EXPOSE 80

